In [2]:
import pandas as pd

brca_csv = pd.read_csv("cleaned_data/merged_brca.csv")
coad_csv = pd.read_csv("cleaned_data/merged_coad.csv")
prad_csv = pd.read_csv("cleaned_data/merged_prad.csv")

In [3]:
brca_csv

,pan.samplesID,Subtype_Selected,ENSG00000000003.15,ENSG00000000005.6,ENSG00000000419.13,ENSG00000000457.14,ENSG00000000460.17,ENSG00000000938.13,ENSG00000000971.16,ENSG00000001036.14,...,ENSG00000288661.1,ENSG00000288662.1,ENSG00000288663.1,ENSG00000288665.1,ENSG00000288667.1,ENSG00000288669.1,ENSG00000288670.1,ENSG00000288671.1,ENSG00000288674.1,ENSG00000288675.1
0,TCGA-E2-A158-11A-22R-A12D-07,BRCA.Normal,1816,682,875,489,149,502,8821,1138,...,0,0,6,0,0,0,328,0,13,7
1,TCGA-BH-A0DD-11A-23R-A12P-07,BRCA.LumA,3303,9914,1127,751,186,1503,13780,1835,...,0,1,13,0,0,1,559,0,9,7
2,TCGA-BH-A1EO-11A-31R-A137-07,BRCA.LumA,6447,3496,3832,1002,370,4520,32887,5966,...,0,0,18,0,0,2,487,0,12,4
3,TCGA-BH-A0B5-11A-23R-A12P-07,BRCA.LumA,3838,1005,1839,844,178,580,7460,2331,...,0,0,25,0,0,0,711,0,12,12
4,TCGA-A7-A13G-11A-51R-A13Q-07,BRCA.LumA,4582,863,1887,1050,239,549,8959,2202,...,0,0,29,0,0,0,716,0,12,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1209,TCGA-UL-AAZ6-01A-11R-A41B-07,BRCA.LumA,938,1,1158,1036,402,213,412,5307,...,0,0,50,0,0,0,298,0,15,43
1210,TCGA-S3-AA0Z-01A-11R-A41B-07,BRCA.Basal,3517,2,2268,2896,2357,632,1389,2195,...,0,0,74,0,0,1,807,0,24,39
1211,TCGA-UU-A93S-01A-21R-A41B-07,BRCA.Her2,350,36,1308,997,518,188,373,1287,...,0,0,8,0,0,0,272,0,8,16
1212,TCGA-BH-A0H9-11A-22R-A466-07,BRCA.Normal,2746,1184,1047,335,81,692,4576,1726,...,0,0,3,0,0,0,359,0,13,8
1213,TCGA-E9-A54Y-01A-11R-A466-07,BRCA.LumB,1288,0,517,366,167,103,60,2102,...,0,0,19,0,2,0,638,0,23,60

In [4]:
coad_csv

,Subtype_Selected,pan.samplesID,ENSG00000000003.15,ENSG00000000005.6,ENSG00000000419.13,ENSG00000000457.14,ENSG00000000460.17,ENSG00000000938.13,ENSG00000000971.16,ENSG00000001036.14,...,ENSG00000288661.1,ENSG00000288662.1,ENSG00000288663.1,ENSG00000288665.1,ENSG00000288667.1,ENSG00000288669.1,ENSG00000288670.1,ENSG00000288671.1,ENSG00000288674.1,ENSG00000288675.1
0,GI.CIN,TCGA-3L-AA1B-01A-11R-A37K-07,7257,23,2058,734,415,247,1548,2785,...,0,0,50,0,0,0,207,0,3,15
1,GI.CIN,TCGA-4N-A93T-01A-11R-A37K-07,7125,67,2626,731,223,71,169,3452,...,0,0,57,0,1,0,405,0,16,29
2,GI.CIN,TCGA-4T-AA8H-01A-11R-A41B-07,2918,89,844,323,190,28,121,1542,...,0,0,44,0,0,0,187,0,1,6
3,GI.CIN,TCGA-5M-AAT4-01A-11R-A41B-07,9897,89,2544,690,691,175,200,3737,...,0,0,49,0,0,0,282,0,3,45
4,GI.CIN,TCGA-5M-AAT5-01A-21R-A41B-07,5301,200,4214,584,655,22,191,3271,...,0,0,55,0,1,0,281,0,4,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,GI.CIN,TCGA-QL-A97D-01A-12R-A41B-07,5351,181,3549,666,580,131,494,1520,...,0,0,46,0,0,0,240,0,4,12
362,GI.CIN,TCGA-RU-A8FL-01A-11R-A37K-07,11038,26,2990,710,381,39,62,5510,...,0,0,45,0,0,0,298,0,4,16
363,GI.CIN,TCGA-SS-A7HO-01A-21R-A37K-07,8315,2,3230,671,666,127,286,2440,...,0,0,118,0,0,2,281,0,4,17
364,GI.CIN,TCGA-T9-A92H-01A-11R-A37K-07,8566,48,4718,584,511,65,258,4073,...,0,0,36,0,0,1,278,0,4,23
365,GI.MSI,TCGA-WS-AB45-01A-11R-A41B-07,1377,1,1146,627,430,2395,7972,2383,...,0,0,11,0,0,1,304,0,3,25

In [5]:
prad_csv

,Subtype_Selected,pan.samplesID,ENSG00000000003.15,ENSG00000000005.6,ENSG00000000419.13,ENSG00000000457.14,ENSG00000000460.17,ENSG00000000938.13,ENSG00000000971.16,ENSG00000001036.14,...,ENSG00000288661.1,ENSG00000288662.1,ENSG00000288663.1,ENSG00000288665.1,ENSG00000288667.1,ENSG00000288669.1,ENSG00000288670.1,ENSG00000288671.1,ENSG00000288674.1,ENSG00000288675.1
0,PRAD.1-ERG,TCGA-HC-7818-01A-11R-2118-07,4053,7,1508,1144,258,596,969,3218,...,0,0,30,0,0,0,398,0,2,24
1,PRAD.1-ERG,TCGA-HC-7077-01A-11R-1965-07,4566,0,1667,1021,160,113,297,3872,...,0,0,7,0,0,0,227,0,5,63
2,PRAD.1-ERG,TCGA-G9-6356-01A-11R-1789-07,4373,7,1371,880,189,423,1850,2753,...,0,0,9,0,0,0,376,0,4,38
3,PRAD.1-ERG,TCGA-G9-6356-11A-01R-1789-07,7212,0,1951,1011,225,266,3337,2017,...,0,0,11,0,0,0,445,0,7,22
4,PRAD.1-ERG,TCGA-HC-7213-01A-11R-2118-07,5915,0,1728,1745,481,310,542,1694,...,0,0,12,0,0,0,345,0,4,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,PRAD.8-other,TCGA-YL-A8SB-01A-31R-A37L-07,2825,21,1589,789,210,182,2085,1509,...,0,0,21,0,0,0,339,0,8,19
376,PRAD.8-other,TCGA-YL-A8SK-01B-21R-A37L-07,4112,3,1601,842,207,249,2556,1430,...,0,0,45,0,0,0,353,0,11,26
377,PRAD.8-other,TCGA-YL-A8SR-01B-11R-A37L-07,3079,0,1872,787,183,579,532,2612,...,0,0,15,0,0,0,270,0,4,22
378,PRAD.8-other,TCGA-YL-A9WJ-01A-11R-A37L-07,2365,9,1462,935,207,529,2411,2564,...,0,0,40,0,0,0,273,0,11,31
379,PRAD.8-other,TCGA-ZG-A8QW-01A-11R-A37L-07,3034,0,1015,382,146,294,848,1969,...,0,0,8,0,0,0,178,0,6,33

In [3]:
y = brca_csv["Subtype_Selected"]
X = brca_csv.drop(columns=["pan.samplesID", "Subtype_Selected"])

In [6]:
y

0       BRCA.Normal
1         BRCA.LumA
2         BRCA.LumA
3         BRCA.LumA
4         BRCA.LumA
           ...
1209      BRCA.LumA
1210     BRCA.Basal
1211      BRCA.Her2
1212    BRCA.Normal
1213      BRCA.LumB
Name: Subtype_Selected, Length: 1214, dtype: str